import React from "react";
export const metadata = {
  title: "Next.js App",
  description: "Generated by Next.js",
};

function Header() {
  return (
    <div>
      {" "}
      <header
        style={{
          padding: "1rem",
          backgroundColor: "lightblue",
        }}
      >
        <h1>{metadata.title}</h1>
        <p>{metadata.description}</p>
      </header>
    </div>
  );
}

export default Header;
